#!/bin/sh
#
# gitflow (https://github.com/nvie/gitflow)
#
# Copyright 2010 Vincent Driessen. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#    1. Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#
#    2. Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY VINCENT DRIESSEN ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL VINCENT DRIESSEN OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
# OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
# NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
# EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# The views and conclusions contained in the software and documentation are
# those of the authors and should not be interpreted as representing official
# policies, either expressed or implied, of Vincent Driessen.

require_git_repo
require_gitflow_initialized
gitflow_load_settings

usage() {
	echo "usage: git blow release"
}

cmd_default() {
	cmd_release
}

cmd_help() {
	usage
	exit 0
}

cmd_release() {
    require_clean_working_tree
    git blow tag
    CURRENT_VERSION=$(git for-each-ref --sort='*authordate' --format='%(refname:short)' refs/tags | tail -n 1)
    if [[ "$CURRENT_VERSION" == *.* ]]; then
        majorpart="${CURRENT_VERSION%.*}."
    else
        majorpart="0.0."
    fi
    minorpart="${CURRENT_VERSION##*.}"
    NEXT_VERSION="$majorpart$((minorpart+1))"

    while true; do
        echo ""
        echo "It would appear that next tag will be \"$NEXT_VERSION\"."
        read -p "Are you sure to bump version to \"$NEXT_VERSION\" [Y/n]? " yn
        case $yn in
            [Yy]* ) git flow release start $NEXT_VERSION && git flow release finish $NEXT_VERSION; break;;
            [Nn]* ) exit;;
            * ) echo "Please answer yes or no.";;
        esac
    done
}
